// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var kind = Props.kind;
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Test"), kind ? React.createElement("p", undefined, "Secondary!") : React.createElement("p", undefined, "Primary"));
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
