// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TailwindCss from "tailwindcss/tailwind.css";

function Button(Props) {
  return React.createElement("div", {
              className: "bg-purple-600"
            }, "Test");
}

var make = Button;

export {
  make ,
  
}
/*  Not a pure module */
