// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button$YourProjectName from "./Button.bs.js";

function Button$dotstories$dollarprimaryButton(Props) {
  return React.createElement(Button$YourProjectName.make, {
              kind: /* Primary */0
            });
}

function Button$dotstories$dollarsecondaryButton(Props) {
  return React.createElement(Button$YourProjectName.make, {
              kind: /* Secondary */1
            });
}

var primaryButton = Button$dotstories$dollarprimaryButton;

var secondaryButton = Button$dotstories$dollarsecondaryButton;

export {
  primaryButton ,
  secondaryButton ,
  
}
/* react Not a pure module */
