// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button$YourProjectName from "./components/Button.bs.js";

function App(Props) {
  return React.createElement(Button$YourProjectName.make, {
              kind: /* Primary */0
            });
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
